DoAnCoSo/Areas/Admin/Controllers/homeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoAnCoSo.Areas.Admin.Controllers
{
    public class homeController : Controller
    {
        // GET: Admin/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

DoAnCoSo/Controllers/DanhMucSanPhamController.cs
using DoAnCoSo.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoAnCoSo.Controllers
{
    public class DanhMucSanPhamController : Controller
    {
        // GET: DanhMucSanPham
        WebTraSuaEntities objWebTraSuaEntities = new WebTraSuaEntities();
        public ActionResult Index()
        {
            var listDanhSachSanPham = objWebTraSuaEntities.DanhMucSanPhams.ToList();
            return View(listDanhSachSanPham);
        }
        public ActionResult SanPhamCategory(int Id)
        {
            var listSanPham = objWebTraSuaEntities.SanPhams.Where(n => n.CategoryId == Id).ToList();
            return View(listSanPham);
        }
    }
}

DoAnCoSo/Controllers/HomeController.cs
using DoAnCoSo.Context;
using DoAnCoSo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace DoAnCoSo.Controllers
{
    public class HomeController : Controller
    {
        WebTraSuaEntities objWebTraSuaEntities = new WebTraSuaEntities();
        public ActionResult Index()
        {
            HomeModel objHomeModel = new HomeModel();
            objHomeModel.listSanPham = objWebTraSuaEntities.SanPhams.ToList();
            objHomeModel.listDanhMucSanPham = objWebTraSuaEntities.DanhMucSanPhams.ToList();
            return View (objHomeModel);
        }

        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(User _user)
        {
            //Kiểm tra và lưu vào database
            if (ModelState.IsValid)
            {
                var check = objWebTraSuaEntities.Users.FirstOrDefault(s => s.Email == _user.Email);
                if (check == null)
                {
                    _user.Password = GetMD5(_user.Password);
                    objWebTraSuaEntities.Configuration.ValidateOnSaveEnabled = false;
                    objWebTraSuaEntities.Users.Add(_user);
                    objWebTraSuaEntities.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.error = "Email already exists";
                    return View();
                }


            }
            return View();
        }
        //Mã hoá password
        public static string GetMD5(string str)
        {
            MD5 md5 = new MD5CryptoServiceProvider();
            byte[] fromData = Encoding.UTF8.GetBytes(str);
            byte[] targetData = md5.ComputeHash(fromData);
            string byte2String = null;

            for (int i = 0; i < targetData.Length; i++)
            {
                byte2String += targetData[i].ToString("x2");

            }
            return byte2String;
        }
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(string email, string password)
        {
            if (ModelState.IsValid)
            {


                var f_password = GetMD5(password);
                var data = objWebTraSuaEntities.Users.Where(s => s.Email.Equals(email) && s.Password.Equals(f_password)).ToList();
                if (data.Count() > 0)
                {
                    //add session
                    Session["FullName"] = data.FirstOrDefault().FirstName + " " + data.FirstOrDefault().LastName;
                    Session["Email"] = data.FirstOrDefault().Email;
                    Session["idUser"] = data.FirstOrDefault().Id;
                    Session["IsAdmin"] = data.FirstOrDefault().IsAdmin;
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.error = "Login failed";
                    return RedirectToAction("Login");
                }
            }
            return View();
        }


        //Logout
        public ActionResult Logout()
        {
            Session.Clear();//remove session
            return RedirectToAction("Login");
        }
    }
}

DoAnCoSo/Controllers/SanPhamController.cs
using DoAnCoSo.Context;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoAnCoSo.Controllers
{
    public class SanPhamController : Controller
    {
        // GET: SanPham
        WebTraSuaEntities objWebTraSuaEntities = new WebTraSuaEntities();
        /*public ActionResult Index(string SearchS  tring)
        {
            var objProduct = objWebTraSuaEntities.SanPhams.Where(n => n.Name.Contains(SearchString)).ToList();
            return View(objProduct);
        }*/

        public ActionResult Index(string SearchString, string currentFilter, int? page)
        {
            var listSanPham = new List<SanPham>();
            if(SearchString != null)
            {
                page = 1;
            }
            else
            {
                SearchString = currentFilter;
            }
            if (!string.IsNullOrEmpty(SearchString))
            {
                //lấy danh sách sản phẩm theo tử khoá tìm kiếm
                listSanPham = objWebTraSuaEntities.SanPhams.Where(n => n.Name.Contains(SearchString)).ToList();
            }
            else
            {
                listSanPham = objWebTraSuaEntities.SanPhams.ToList();
            }
            ViewBag.CurrentFilter = SearchString;
            int pageSize = 4;
            int pageNumber = (page ?? 1);
            listSanPham = listSanPham.OrderByDescending(n => n.Id).ToList();
            return View(listSanPham.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Detail(int Id)
        {
            var objSanPham = objWebTraSuaEntities.SanPhams.Where(n => n.Id == Id).FirstOrDefault();
            return View(objSanPham);
        }

        
    }
}

DoAnCoSo/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

DoAnCoSo/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DoAnCoSo/Views/Home/Index.cshtml
@model DoAnCoSo.Models.HomeModel


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <!-- ========================= SECTION MAIN  ========================= -->
    <section class="section-main padding-y">
        <main class="card">
            <div class="card-body">

                <div class="row">
                    <aside class="col-lg col-md-3 flex-lg-grow-0">
                        <h6>Danh mục</h6>
                        <nav class="nav-home-aside">
                            <ul class="menu-category">
                                @foreach (var item in Model.listDanhMucSanPham)
                                {
                                    <li>
                                        @Html.ActionLink(item.Name,"SanPhamCategory", "DanhMucSanPham", new {@Id = item.Id},null)
                                    </li>
                                }
                            </ul>
                        </nav>
                    </aside> <!-- col.// -->
                    <div class="col-md-9 col-xl-7 col-lg-7">

                        <!-- ================== COMPONENT SLIDER  BOOTSTRAP  ==================  -->
                        <div id="carousel1_indicator" class="slider-home-banner carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel1_indicator" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel1_indicator" data-slide-to="1"></li>
                                <li data-target="#carousel1_indicator" data-slide-to="2"></li>
                            </ol>
                           
                            <div class="carousel-inner">
                                <div class="carousel-item active">
                                    <img src="~/Content/images/banner/choco.799x500-01.jpg" alt="First slide">
                                </div>
                                <div class="carousel-item">
                                    <img src="~/Content/images/banner/straw799x500-1400x876.jpg" alt="Second slide">
                                </div>
                                <div class="carousel-item">
                                    <img src="~/Content/images/banner/toffee.799x500-01.jpg" alt="Third slide">
                                </div>
                            </div>
                            <a class="carousel-control-prev" href="#carousel1_indicator" role="button" data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#carousel1_indicator" role="button" data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                        <!-- ==================  COMPONENT SLIDER BOOTSTRAP end.// ==================  .// -->

                    </div> <!-- col.// -->
                    <div class="col-md d-none d-lg-block flex-grow-1">
                        <aside class="special-home-right">
                            <h6 class="bg-blue text-center text-white mb-0 p-2">ĐỒ ĂN THỨC UỐNG NỔI BẬC</h6>
                            @foreach (var item in Model.listDanhMucSanPham.Where(n=> n.ShowOnHomePage==true))
                            {
                        <div class="card-banner border-bottom">
                            <div class="py-3" style="width:80%">
                                <h6 class="card-title">@item.Name</h6>
                                <a href="#" class="btn btn-secondary btn-sm"> Source now </a>
                            </div>
                            <img src="@item.Avatar" height="80" class="img-bg">
                        </div>
                            }



                        </aside>
                    </div> <!-- col.// -->
                </div> <!-- row.// -->

            </div> <!-- card-body.// -->
        </main> <!-- card.// -->

    </section>
    <!-- ========================= SECTION MAIN END// ========================= -->
    <!-- =============== SECTION DEAL =============== -->
    <section class="padding-bottom">
        <div class="card card-deal">
       @*     <div class="col-heading content-body">
                <header class="section-heading">
                    <h3 class="section-title">Khuyến mãi</h3>
                    <p>Hygiene equipments</p>
                </header> sect-heading 
                <div class="timer">
                    <div> <span class="num">04</span> <small>Days</small></div>
                    <div> <span class="num">12</span> <small>Hours</small></div>
                    <div> <span class="num">58</span> <small>Min</small></div>
                    <div> <span class="num">02</span> <small>Sec</small></div>
                </div>
            </div> *@
            <div class="row no-gutters items-wrap">

                @foreach (var item in Model.listSanPham.Where(n=> n.TypeId == 1).Take(5))
                {
                    <div class="col-md col-6">
                        <figure class="card-product-grid card-sm">
                            <a href="@Url.Action("Detail","SanPham",new {Id = item.Id })" class="img-wrap">
                                <img src="@item.Avartar">
                            </a>
                            <div class="text-wrap p-3">
                                <a href="#" class="title">@item.Name</a>
                                <span class="badge badge-danger"> -20% </span>
                               
                            </div>
                        </figure>
                    </div> <!-- col.// -->
                }
            </div>
        </div>

    </section>
    <!-- =============== SECTION DEAL // END =============== -->
    <!-- =============== SECTION 1 =============== -->
    <section class="padding-bottom">
        <header class="section-heading heading-line">
            <h4 class="title-section text-uppercase">Trà Sữa</h4>
        </header>

        <div class="card card-home-category">
            <div class="row no-gutters">
                <div class="col-md-3">

                    <div class="home-category-banner bg-light-orange">
                        <h5 class="title">Best trending clothes only for summer</h5>
                        <p>Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                        <a href="#" class="btn btn-outline-primary rounded-pill">Source now</a>
                        <img style="width:200px" src="~/Content/images/TS.png" />
                        
                    </div>

                </div> <!-- col.// -->
                <div class="col-md-9">
                    <ul class="row no-gutters bordered-cols">
                        @foreach (var item in Model.listSanPham.Where(n=>n.CategoryId == 2))
                        {
                            <li class="col-6 col-lg-3 col-md-4">
                                <a href="@Url.Action("Detail","SanPham",new {Id = item.Id })" class="item">
                                    <div class="card-body">
                                        <h6 class="title">Well made women clothes with trending collection  </h6>
                                        <img class="img-sm float-right" src="@item.Avartar">
                                        <p class="text-muted"><i class="fa fa-map-marker-alt"></i> @item.Name</p>
                                    </div>
                                </a>
                            </li>
                        }
                    </ul>
                </div> <!-- col.// -->
            </div> <!-- row.// -->
        </div> <!-- card.// -->
    </section>
    <!-- =============== SECTION 1 END =============== -->
    <!-- =============== SECTION 2 =============== -->
    <section class="padding-bottom">
        <header class="section-heading heading-line">
            <h4 class="title-section text-uppercase">Kem</h4>
        </header>

        <div class="card card-home-category">
            <div class="row no-gutters">
                <div class="col-md-3">

                    <div class="home-category-banner bg-light-orange">
                        <h5 class="title">Machinery items for manufacturers</h5>
                        <p>Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                        <a href="#" class="btn btn-outline-primary rounded-pill">Source now</a>
                        <img style="width:200px" src="~/Content/images/kem.png" />
                    </div>

                </div> <!-- col.// -->
                <div class="col-md-9">
                    <ul class="row no-gutters bordered-cols">
                        @foreach (var item in Model.listSanPham.Where(n => n.CategoryId == 1))
                        {
                            <li class="col-6 col-lg-3 col-md-4">
                                <a href="@Url.Action("Detail","SanPham",new {Id = item.Id })" class="item">
                                    <div class="card-body">
                                        <h6 class="title">Well made women clothes with trending collection  </h6>
                                        <img class="img-sm float-right" src="@item.Avartar">
                                        <p class="text-muted"><i class="fa fa-map-marker-alt"></i> @item.Name</p>
                                    </div>
                                </a>
                            </li>
                        }
                    </ul>
                </div> <!-- col.// -->
            </div> <!-- row.// -->
        </div> <!-- card.// -->
    </section>
    <!-- =============== SECTION 2 END =============== -->
   
    <!-- =============== SECTION ITEMS =============== -->
    <section class="padding-bottom-sm">

        <header class="section-heading heading-line">
            <h4 class="title-section text-uppercase">Đồ ăn vặt</h4>
        </header>

        <div class="row row-sm">
            <div class="col-xl-2 col-lg-3 col-md-4 col-6">
                <div href="#" class="card card-sm card-product-grid">
                    <a href="#" class="img-wrap">
                    <img style="width:200px" src="~/Content/images/anvat.jpg" />
                        <figcaption class="info-wrap">
                            <a href="#" class="title">Just another product name</a>
                            <div class="price mt-1">$179.00</div> <!-- price-wrap.// -->
                        </figcaption>
</div>
            </div> <!-- col.// -->
            @foreach (var item in Model.listSanPham.Where(n=> n.CategoryId==3).Take(3))
            {
                <li class="col-6 col-lg-3 col-md-4">
                    <a href="@Url.Action("Detail","SanPham",new {Id = item.Id })" class="item">
                        <div class="card-body">
                            <h6 class="title">Well made women clothes with trending collection  </h6>
                            <img class="img-sm float-right" src="@item.Avartar">
                            <p class="text-muted"><i class="fa fa-map-marker-alt"></i> @item.Name</p>
                        </div>
                    </a>
                </li>
            }
        </div> <!-- row.// -->
    </section>

</div>
<!-- container end.// -->
<!-- ========================= SECTION SUBSCRIBE  ========================= -->
<section class="section-subscribe padding-y-lg">
    <div class="container">

        <p class="pb-2 text-center text-white">Delivering the latest product trends and industry news straight to your inbox</p>

        <div class="row justify-content-md-center">
            <div class="col-lg-5 col-md-6">
                <form class="form-row">
                    <div class="col-md-8 col-7">
                        <input class="form-control border-0" placeholder="Your Email" type="email">
                    </div> <!-- col.// -->
                    <div class="col-md-4 col-5">
                        <button type="submit" class="btn btn-block btn-warning"> <i class="fa fa-envelope"></i> Subscribe </button>
                    </div> <!-- col.// -->
                </form>
                <small class="form-text text-white-50">We’ll never share your email address with a third-party. </small>
            </div> <!-- col-md-6.// -->
        </div>


    </div>
</section>
<!-- ========================= SECTION SUBSCRIBE END// ========================= -->
<!-- ========================= FOOTER ========================= -->

DoAnCoSo/Views/Home/Login.cshtml
@model DoAnCoSo.Context.User

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    


<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->
    <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
        <div class="card-body">
            <h4 class="card-title mb-4">Sign in</h4>
            @using (Html.BeginForm("Login", "Home", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <form>
                    <a href="#" class="btn btn-facebook btn-block mb-2"> <i class="fab fa-facebook-f"></i> &nbsp  Sign in with Facebook</a>
                    <a href="#" class="btn btn-google btn-block mb-4"> <i class="fab fa-google"></i> &nbsp  Sign in with Google</a>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Email)
                        @Html.TextBoxFor(m => m.Email, "", new { @class = "form-control", @placeholder = "Email" })
                    </div> <!-- form-group// -->
                    <div class="form-group">
                        @Html.LabelFor(m => m.Password)
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Password" })
                    </div> <!-- form-group// -->

                    <div class="form-group">
                        <a href="#" class="float-right">Forgot password?</a>
                        <label class="float-left custom-control custom-checkbox"> <input type="checkbox" class="custom-control-input" checked=""> <div class="custom-control-label"> Remember </div> </label>
                    </div> <!-- form-group form-check .// -->
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block"> Login  </button>
                    </div> <!-- form-group// -->
                </form>
            }
        </div> <!-- card-body.// -->
    </div> <!-- card .// -->

    <p class="text-center mt-4">Don't have account? <a href="~/Home/Register">Sign up</a></p>
    <br><br>
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

DoAnCoSo/Views/Home/Register.cshtml
@model DoAnCoSo.Context.User

@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Register</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <!-- ========================= SECTION CONTENT ========================= -->
    <section class="section-content padding-y">

        <!-- ============================ COMPONENT REGISTER   ================================= -->
        <div class="card mx-auto" style="max-width:520px; margin-top:40px;">
            <article class="card-body">
                <header class="mb-4"><h4 class="card-title">Sign up</h4></header>
                <form>
                    <div class="form-group">
                        @*@Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })*@
                        <p class="control-label">Họ</p>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <p class="control-label">Tên</p>
                        @*@Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })*@
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })*@
                        <p class="control-label">Email</p>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })*@
                        <p class="control-label">Mật khẩu</p>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { Type = "Password", @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    
                    <div class="form-group">
                        @*@Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })*@
                        <p class="control-label">Xác nhận mật khẩu</p>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { Type = "Password", @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            @*@Html.LabelFor(model => model.IsAdmin, htmlAttributes: new { @class = "control-label col-md-2" })*@
                            <p class="control-label"> Quyền truy cập</p>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.IsAdmin, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.IsAdmin, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Đăng ký" class="btn btn-success" />
                            </div>
                        </div>
                </form>
            </article><!-- card-body.// -->
        </div> <!-- card .// -->
        <p class="text-center mt-4">Have an account? <a href="~/Home/Login">Log In</a></p>
        <br><br>
        <!-- ============================ COMPONENT REGISTER  END.// ================================= -->


    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>