DoAnCoSo/Areas/Admin/Controllers/LoaiSanPhamController.cs
using DoAnCoSo.Context;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoAnCoSo.Areas.Admin.Controllers
{
    public class LoaiSanPhamController : Controller
    {
        // GET: Admin/LoaiSanPham
        WebTraSuaEntities objWebTraSuaEntities = new WebTraSuaEntities();
        public ActionResult Index()
        {
            if (Session["idUser"] != null && Session["IsAdmin"] != null)
            {
                var objLoaiSanPham = objWebTraSuaEntities.LoaiSanPhams.ToList();
            return View(objLoaiSanPham);
            }
            else
            {
                return Redirect("~/Home/Login");
            }
        }
        [HttpGet]
        public ActionResult Create()
        {

                if (Session["idUser"] != null && Session["IsAdmin"] != null)
                {
                    LoaiSanPham loaisp = new LoaiSanPham();
            return View(loaisp);
            }
            else
            {
                return Redirect("~/Home/Login");
            }
        }
        [HttpPost]
        public ActionResult Create(LoaiSanPham objLoaiSanPham)
        {
            try
            {
                if (objLoaiSanPham.ImageUpload != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(objLoaiSanPham.ImageUpload.FileName);
                    string extension = Path.GetExtension(objLoaiSanPham.ImageUpload.FileName);
                    fileName = fileName + extension;
                    objLoaiSanPham.Avatar = "~/Content/images/" + fileName;
                    objLoaiSanPham.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/Content/images/"), fileName));
                }
                objWebTraSuaEntities.LoaiSanPhams.Add(objLoaiSanPham);
                objWebTraSuaEntities.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return View();
            }
        }
        [HttpGet]
        public ActionResult Detail(int id)

        {

                    if (Session["idUser"] != null && Session["IsAdmin"] != null)
                    {
                        var objLoaiSanPham = objWebTraSuaEntities.LoaiSanPhams.Where(n => n.Id == id).FirstOrDefault();
            return View(objLoaiSanPham);
            }
            else
            {
                return Redirect("~/Home/Login");
            }
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {

                    if (Session["idUser"] != null && Session["IsAdmin"] != null)
                    {
                        var objLoaiSanPham = objWebTraSuaEntities.LoaiSanPhams.Where(n => n.Id == id).FirstOrDefault();
            return View(objLoaiSanPham);
            }
            else
            {
                return Redirect("~/Home/Login");
            }
        }
        [HttpPost]
        public ActionResult Delete(LoaiSanPham objlsp)
        {
            var objLoaiSanPham = objWebTraSuaEntities.LoaiSanPhams.Where(n => n.Id == objlsp.Id).FirstOrDefault();
            objWebTraSuaEntities.LoaiSanPhams.Remove(objLoaiSanPham);
            objWebTraSuaEntities.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {

            if (Session["idUser"] != null && Session["IsAdmin"] != null)
            {
                var objLoaiSanPham = objWebTraSuaEntities.LoaiSanPhams.Where(n => n.Id == id).FirstOrDefault();
            return View(objLoaiSanPham);
        }
            else
            {
                return Redirect("~/Home/Login");

    }
}
        [HttpPost]
        public ActionResult Edit(LoaiSanPham objLoaiSanPham)
        {

            if (objLoaiSanPham.ImageUpload != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(objLoaiSanPham.ImageUpload.FileName);
                string extension = Path.GetExtension(objLoaiSanPham.ImageUpload.FileName);
                fileName = fileName + extension;
                objLoaiSanPham.Avatar = "~/Content/images/" + fileName;
                objLoaiSanPham.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/Content/images/"), fileName));
            }
            objWebTraSuaEntities.Entry(objLoaiSanPham).State = EntityState.Modified;
            objWebTraSuaEntities.SaveChanges();
            return View(objLoaiSanPham);
        }
    }
}

DoAnCoSo/Areas/Admin/Views/LoaiSanPham/Create.cshtml
@model DoAnCoSo.Context.LoaiSanPham

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align:center">THÊM LOẠI SẢN PHẨM</h2>

@using (Html.BeginForm("Create", "LoaiSanPham", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal container">
        <h4>LoaiSanPham</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Avatar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img style="width:100px" src="@Url.Content(Model.Avatar)" id="previewImage" />
                <input type="file" name="ImageUpload" onchange="ShowImagePreview(this, document.getElementById('previewImage'))" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Slug, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Slug, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Slug, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShowOnHomePage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShowOnHomePage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShowOnHomePage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DisplayOrder, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DisplayOrder, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DisplayOrder, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateOnUtc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateOnUtc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateOnUtc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UpdateOnUtc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UpdateOnUtc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdateOnUtc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Delete, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Delete, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Delete, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DoAnCoSo/Areas/Admin/Views/LoaiSanPham/Delete.cshtml
@model DoAnCoSo.Context.LoaiSanPham

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align:center">XOÁ LOẠI SẢN PHẨM</h2>


<div class="container">
    <h4>LoaiSanPham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Avatar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Avatar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Slug)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Slug)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShowOnHomePage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShowOnHomePage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DisplayOrder)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DisplayOrder)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateOnUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateOnUtc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdateOnUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateOnUtc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Delete)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Delete)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DoAnCoSo/Areas/Admin/Views/LoaiSanPham/Detail.cshtml
@model DoAnCoSo.Context.LoaiSanPham

@{
    ViewBag.Title = "Detail";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align:center">CHI TIẾT</h2>

<div class="container">
    <h4>LoaiSanPham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Avatar)
        </dt>

        <dd>
            <img src="@Model.Avatar" style="width:200px" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Slug)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Slug)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShowOnHomePage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShowOnHomePage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DisplayOrder)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DisplayOrder)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateOnUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateOnUtc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdateOnUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateOnUtc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Delete)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Delete)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DoAnCoSo/Areas/Admin/Views/LoaiSanPham/Edit.cshtml
@model DoAnCoSo.Context.LoaiSanPham

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align:center">CHỈNH SỬA</h2>

@using (Html.BeginForm("Edit", "LoaiSanPham", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal container">
        <h4>LoaiSanPham</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Avatar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img style="width:100px" src="@Url.Content(Model.Avatar)" id="previewImage" />
                <input type="file" name="ImageUpload" onchange="ShowImagePreview(this, document.getElementById('previewImage'))" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Slug, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Slug, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Slug, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShowOnHomePage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShowOnHomePage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShowOnHomePage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DisplayOrder, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DisplayOrder, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DisplayOrder, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateOnUtc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateOnUtc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateOnUtc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UpdateOnUtc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UpdateOnUtc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdateOnUtc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Delete, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Delete, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Delete, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<img src="~/Content/images/logoAnVat.png" />
<img src="~/Content/images/logoTS.jpg" />

DoAnCoSo/Areas/Admin/Views/LoaiSanPham/Index.cshtml
@model IEnumerable<DoAnCoSo.Context.LoaiSanPham>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align:center">Danh mục loại sản phẩm</h2>

<p class="btn" style="margin-left:400px; padding:4px; background-color:aqua; color:black">
    @Html.ActionLink("Create New", "Create")
</p>

<table class="table container">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Avatar)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Slug)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShowOnHomePage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DisplayOrder)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreateOnUtc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UpdateOnUtc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Delete)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            <img width="200px" src="@item.Avatar" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Slug)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ShowOnHomePage)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DisplayOrder)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreateOnUtc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UpdateOnUtc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Delete)
            <th>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id })
            </th>
            <th>
                @Html.ActionLink("Detail", "Detail", new { id = item.Id }) 
            </th>
            <th>
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </th>
        </td>
    </tr>
}

</table>